const TERRARIA_INVENTORY_SLOTS = 59;
const TERRARIA_ARMOR_SLOTS = 20;
const TERRARIA_DYE_SLOTS = 10;
const TERRARIA_MISC_EQUIP_SLOTS = 5;
const TERRARIA_MISC_DYE_SLOTS = 5;
const TERRARIA_BANK_COUNT = 4;
const TERRARIA_BANK_SLOTS = 40;
const TERRARIA_TRASH_SLOTS = 1;
const TERRARIA_LOADOUT_COUNT = 3;

const TERRARIA_FULL_PLAYER_INVENTORY_PACKETS =
  TERRARIA_INVENTORY_SLOTS +
  TERRARIA_ARMOR_SLOTS +
  TERRARIA_DYE_SLOTS +
  TERRARIA_MISC_EQUIP_SLOTS +
  TERRARIA_MISC_DYE_SLOTS +
  TERRARIA_BANK_COUNT * TERRARIA_BANK_SLOTS +
  TERRARIA_TRASH_SLOTS +
  TERRARIA_LOADOUT_COUNT * (TERRARIA_ARMOR_SLOTS + TERRARIA_DYE_SLOTS);

// A production join capture against eu-lim-1 showed five full player inventory
// bursts queued before spawn. Keep one extra full burst of packet-count margin.
const OBSERVED_PRE_READY_INVENTORY_BURSTS = 5;
const PRE_READY_INVENTORY_BURST_MARGIN = 1;

export const MAX_PRE_READY_QUEUE_PACKETS =
  TERRARIA_FULL_PLAYER_INVENTORY_PACKETS *
  (OBSERVED_PRE_READY_INVENTORY_BURSTS + PRE_READY_INVENTORY_BURST_MARGIN);

export const MAX_PRE_READY_QUEUE_BYTES = 65536;
