define(function() {
  var PacketTypes = {
    1: "Connect Request",
    2: "Disconnect",
    3: "Continue Connecting",
    4: "Player Info",
    5: "Player Inventory Slot",
    6: "Continue Connecting 2",
    7: "World Info",
    8: "Get Section/Request Sync",
    9: "Status",
    10: "Send Section",
    11: "Section Tile Frame",
    12: "Spawn Player",
    13: "Update Player",
    14: "Player Active",
    15: "Null",
    16: "Player HP",
    17: "Modify Tile",
    18: "Time",
    19: "Door Toggle",
    20: "Send Tile Square",
    21: "Update Item Drop",
    22: "Update Item Owner",
    23: "NPC Update",
    24: "Strike NPC with Held Item",
    25: "Chat Message",
    26: "Player Damage",
    27: "Projectile Update",
    28: "NPC Strike",
    29: "Destroy Projectile",
    30: "Toggle PVP",
    31: "Get Chest Contents/Active Chest",
    32: "Chest Item",
    33: "Set Chest Name/Open Chest",
    34: "Place/Kill Chest",
    35: "Heal Effect",
    36: "Player Zone",
    37: "Request Password",
    38: "Send Password",
    39: "Remove Item Owner",
    40: "Set Active NPC",
    41: "Player Item Animation",
    42: "Player Mana",
    43: "Mana Effect",
    44: "Kill Me",
    45: "Player Team",
    46: "Request Sign",
    47: "Update/Display Sign",
    48: "Set Liquid",
    49: "Complete Connection and Spawn",
    50: "Update Player Buff",
    51: "Special NPC Effect",
    52: "Unlock",
    53: "Add NPC Buff",
    54: "Update NPC Buff",
    55: "Add Player Buff",
    56: "Update NPC Name",
    57: "Update Good/Evil",
    58: "Play Music Item",
    59: "Hit Switch",
    60: "NPC Home Update",
    61: "Spawn Boss/Invasion",
    62: "Player Dodge",
    63: "Paint Tile",
    64: "Paint Wall",
    65: "Player/NPC Teleport",
    66: "Heal Other Player",
    67: "Client Remote Address",
    68: "Client UUID",
    69: "Get Chest Name",
    70: "Catch NPC(bugs)",
    71: "Release NPC",
    72: "Travelling Merchant Inventory",
    73: "Teleportation Potion",
    74: "Angler Quest",
    75: "Complete Angler quest today",
    76: "Number Of Angler Quests Completed",
    77: "Create Temporary Animation",
    78: "Report Invasion Progress",
    79: "Place Object",
    80: "Sync Player Chest Index",
    81: "Create Combat Text",
    82: "Load NetModule",
    83: "Set NPC Kill Count",
    84: "Set Player Stealth",
    85: "Force Item Into Nearest Chest",
    86: "UpdateTile Entity",
    87: "PlaceTile Entity",
    88: "Alter Item Drop",
    89: "Place Item Frame",
    90: "Update Item Drop - Instanced",
    91: "Sync Emote Bubble",
    92: "Sync Extra Value",
    93: "Social Handshake",
    94: "Deprecated",
    95: "Kill Portal",
    96: "Player Teleport Through Portal",
    97: "Notify Player NPC Killed",
    98: "Notify Player Of Event",
    99: "Update Minion Target",
    100: "NPC Teleport Through Portal",
    101: "Update Shield Strengths",
    102: "Nebula Level Up Request",
    103: "Update Moon Lord Countdown",
    104: "Set NPC Shop Item",
    105: "Toggle Gem Lock",
    106: "Poof of Smoke",
    107: "Chat Message",
    108: "Wired Cannon Shot",
    109: "Mass Wire Operation",
    110: "Mass Wire Operation Consume",
  };

  return PacketTypes;
});
